version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.amazonaws:*"
      - dependency-name: "software.amazon.awssdk:*"
