rootProject.name = "awstestkit"

include("core:common")
include("core:v1")
include("core:v2")
include("documentation")
include("localstack")
include("cloudformation")
include("dynamodb")
include("firehose")
include("kinesis")
include("kms")
include("s3")
include("secretsmanager")
include("ses")
include("sns")
include("sqs")
